In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np

In [4]:
list=np.array([1,2,3,4,5])
list[0]

1

In [5]:
list+2

array([3, 4, 5, 6, 7])

In [6]:
list*3

array([ 3,  6,  9, 12, 15])

In [7]:
list/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [11]:
np.flip(list)

array([5, 4, 3, 2, 1])

In [17]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [18]:
count= np.bincount(x)
most_freq= np.argmax(count)
most_freq

1

In [25]:
count= np.bincount(y)
most_freq= np.argmax(count)
most_freq


1

In [26]:
np.where(x==most_freq)[0]

array([0, 5, 7, 8, 9])

In [28]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [30]:
arr[0][1]

20

In [31]:
arr[2][0]

70

In [33]:
yash= np.linspace(10,100,25)
yash

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [37]:
yash.ndim

1

In [41]:
np.shape(yash)
yash.shape

(25,)

In [43]:
yash.size

25

In [46]:
yash.dtype

dtype('float64')

In [47]:
yash.nbytes

200

In [55]:
yash_reshaped= yash.reshape(5,5)
yash_reshaped

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ],
       [ 28.75,  32.5 ,  36.25,  40.  ,  43.75],
       [ 47.5 ,  51.25,  55.  ,  58.75,  62.5 ],
       [ 66.25,  70.  ,  73.75,  77.5 ,  81.25],
       [ 85.  ,  88.75,  92.5 ,  96.25, 100.  ]])

In [56]:
yash_reshaped.T

array([[ 10.  ,  28.75,  47.5 ,  66.25,  85.  ],
       [ 13.75,  32.5 ,  51.25,  70.  ,  88.75],
       [ 17.5 ,  36.25,  55.  ,  73.75,  92.5 ],
       [ 21.25,  40.  ,  58.75,  77.5 ,  96.25],
       [ 25.  ,  43.75,  62.5 ,  81.25, 100.  ]])

In [58]:
list= np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
ucs420_yash= list.reshape(3,4)
ucs420_yash

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [63]:
ucs420_yash.mean()

43.333333333333336

In [64]:
ucs420_yash.max()

90

In [65]:
ucs420_yash.min()

10

In [69]:
np.unique(list)

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [78]:
yash_reshaped=ucs420_yash.reshape(4,3)
yash_reshaped

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [76]:
resized_yash= np.resize(yash_reshaped,(2,3))
resized_yash

array([[10, 20, 30],
       [40, 50, 60]])